import Head from 'next/head'
import { Josefin_Sans } from "@next/font/google"
import '@/styles/globals.css'

const josefinSans = Josefin_Sans({
  subsets : ['latin'],
  weight : ['400', '700'],
  variable : '--font-josefin'
})
export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>FEM Todo App | Rifky Niyas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${josefinSans.variable} font-sans`}>
        <Component {...pageProps} />
      </div>
    </>
  )
}
